# Generated by Django 5.1.7 on 2025-03-11 20:59

from django.db import migrations

def create_initial_data(apps, schema_editor):
    # Get our models
    Role = apps.get_model('api', 'Role')
    Team = apps.get_model('api', 'Team')
    Member = apps.get_model('api', 'Member')
    TeamMember = apps.get_model('api', 'TeamMember')

    # Create roles
    admin_role = Role.objects.create(code='ADMIN', name='Admin')
    regular_role = Role.objects.create(code='REGULAR', name='Regular')

    # Create teams
    sales_team = Team.objects.create(name='Sales')
    marketing_team = Team.objects.create(name='Marketing')

    # Create members
    joe = Member.objects.create(
        first_name='Joe',
        last_name='Sales',
        email='joe.sales@example.com',
        phone_number='555-0001'
    )
    mary = Member.objects.create(
        first_name='Mary',
        last_name='Sales',
        email='mary.sales@example.com',
        phone_number='555-0002'
    )
    peter = Member.objects.create(
        first_name='Peter',
        last_name='Marketing',
        email='peter.marketing@example.com',
        phone_number='555-0003'
    )
    susan = Member.objects.create(
        first_name='Susan',
        last_name='Marketing',
        email='susan.marketing@example.com',
        phone_number='555-0004'
    )

    # Create team memberships
    TeamMember.objects.create(team=sales_team, member=joe, role=regular_role)
    TeamMember.objects.create(team=sales_team, member=mary, role=regular_role)
    TeamMember.objects.create(team=marketing_team, member=peter, role=regular_role)
    TeamMember.objects.create(team=marketing_team, member=susan, role=regular_role)

def remove_initial_data(apps, schema_editor):
    # Get our models
    Role = apps.get_model('api', 'Role')
    Team = apps.get_model('api', 'Team')
    Member = apps.get_model('api', 'Member')
    TeamMember = apps.get_model('api', 'TeamMember')

    # Remove all data
    TeamMember.objects.all().delete()
    Member.objects.all().delete()
    Team.objects.all().delete()
    Role.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, remove_initial_data),
    ]
